name: Entur/Security/CI

on:
    pull_request:

jobs:
    update-code_scanning-doc:
        uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1.0.0
        with: 
            workflow_file: .github/workflows/code_scanning.yml
            readme_file: README-code_scanning.md